# No Copyright (-) 2010 The Ampify Authors. This file is under the
# Public Domain license that can be found in the root LICENSE file.

review_server: http://localhost:8090
cc: ampify@googlegroups.com
default_branch: master

slave:
- ['init', './environ/amp', 'build']
- ['py-tests', './environ/amp', 'test', 'python']
- ['go-tests', './environ/amp', 'test', 'go']
